# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Install dependencies first (for better caching)
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Default port
ENV PORT=8080

# Make sure we listen on PORT environment variable 
# (Smithery will set this during deployment)
EXPOSE ${PORT}

# Start the FastAPI server
CMD ["sh", "-c", "python gemini_server.py"]
