# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy requirements file and install dependencies
COPY mcp-chatgpt-responses/requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of the application code
COPY mcp-chatgpt-responses/. ./

# Expose port if necessary (not strictly required for stdio servers)

# Command to run the MCP server
CMD ["python", "gemini_server.py"]
